backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Продукти"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Име", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Цена", name: "price", widget: "string" }
      - { label: "Снимка", name: "image", widget: "image" }
